version: '3.8'

services:
  vibevoice:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
        WORKDIR: /workspace/zhao-kun/vibevoice
        GITHUB_REPO: https://github.com/zhao-kun/vibevoice.git
        GITHUB_BRANCH: main
    image: vibevoice:latest
    container_name: vibevoice
    ports:
      - "9527:9527"
    volumes:
      # Persist workspace data (projects, voices, generated audio)
      - ./workspace:/workspace/zhao-kun/vibevoice/workspace
      # Optional: Mount models directory if you want to use local models
      # - ./models:/workspace/zhao-kun/vibevoice/models
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9527/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
